apiVersion: v1
kind: Service
metadata:
  name: flask-spark-service
spec:
  selector:
    app: flask-spark
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-spark
spec:
  selector:
    matchLabels:
      app: flask-spark
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-spark
    spec:
      containers:
      - name: flask-spark
        image: flask-spark:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080